name: sonidos_sgo
description: Reto para Programación 3.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.0
    

  english_words: ^4.0.0
  provider: ^6.0.0
  url_launcher: ^6.2.5
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.0.14
  share_plus: ^7.0.2
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/audio/
    - lib/assets/logos/sandrixEIRL.jpg

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
